spring:
  mvc:
    problemdetails:
      enabled: true
  #  datasource:
  #    url: jdbc:postgresql://192.168.3.44:5432/dummy_json
  #    username: postgres
  #    password: 1801
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
  security:
    user:
      password: 1801
      name: duberly
logging:
  level:
    org.springframework.security: trace

jwt_key: ${JWT_KEY}
hostname: "duberlyguarnizo.com"
