spring:
  messages:
    basename: "lang/messages"
  mvc:
    problemdetails:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always

server:
  servlet:
    encoding:
      force: true

logging:
  level:
    org.springframework.security: trace

jwt_key: ${JWT_KEY}
hostname: "duberlyguarnizo.com"


